### ISSUE TITLE
How to reconstruct FOD file

### ISSUE THREAD

**Issue by Luoyu-Wang** [schillkg/HARFI_Scripts#2]
Hi, we have used your code to put our fmri data to generate the  spherical harmonic coefficients like SH_even4, SH_odd4, SH_norm_even4, and SH_norm_odd4, SH_norm_odd4. How can we reconstruct all FODs that could be visualised by mrtrix3 using the full complement of spherical harmonic coefficients (even and odd order),? Thank you very much for your guidance!

**Comment by schillkg** [comment]
You can view these using matlab tools (for example: https://github.com/justinblaber/dwmri_visualizer) or using any standard SH viewer (for example, MrTrix3) after re-organizing the SH coefficients.
